# Generated by Django 5.2.8 on 2026-01-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
