# Generated by Django 5.2.8 on 2026-01-19 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Administrateur', 'Administrateur'), ('Moderateur', 'Modérateur'), ('Utilisateur', 'Utilisateur')], default='Utilisateur', max_length=20),
        ),
    ]
