# # Generated by Django 5.2.8 on 2026-01-23 11:20



from django.db import migrations

def create_default_menus(apps, schema_editor):
    Role = apps.get_model('app_contact', 'Role')
    
    data = [
        ('administrateur', 'administrateur'),
        ('Moderateur', 'Moderateur'),
        ('Utilisateur', 'Utilisateur'),
        ('Responsable de Saisie', 'Responsable de Saisie'),    
    ]    
    
    for nom, code in data:
        Role.objects.get_or_create(nom_role=code, defaults={'nom_role': nom})

class Migration(migrations.Migration):
    # dependencies = [('app_user', '0005_role_alter_user_nom_alter_user_password_and_more')]
    dependencies = [
        ('app_contact', '0005_role_alter_user_nom_alter_user_password_and_more'),
    ]    
    operations = [migrations.RunPython(create_default_menus)]
    
    
    
    