# # # Generated by Django 5.2.8 on 2026-01-24 09:35


################################################################

# Désormais, ton administrateur est inscrit en base de données de manière permanente.

# Désormais, ton administrateur est inscrit en base de données de manière permanente.

# Désormais, ton administrateur est inscrit en base de données de manière permanente.

# Désormais, ton administrateur est inscrit en base de données de manière permanente.

# Désormais, ton administrateur est inscrit en base de données de manière permanente.




# https://gemini.google.com/app/5a9a859ff2a2f94e
# https://gemini.google.com/app/5a9a859ff2a2f94e
# https://gemini.google.com/app/5a9a859ff2a2f94e

# https://gemini.google.com/app/5a9a859ff2a2f94e
# https://gemini.google.com/app/5a9a859ff2a2f94e
# https://gemini.google.com/app/5a9a859ff2a2f94e
# https://gemini.google.com/app/5a9a859ff2a2f94e

# 0006_table_role_de_user.py


################################################################


from django.db import migrations
from django.contrib.auth.hashers import make_password

def creer_admin_par_defaut(apps, schema_editor):
    # On récupère les modèles via 'apps' pour être sûr d'utiliser la bonne version
    User = apps.get_model('app_contact', 'User')
    Role = apps.get_model('app_contact', 'Role')

    # 1. Créer le rôle Administrateur
    role_admin, _ = Role.objects.get_or_create(nom_role="administrateur")

    # 2. Créer l'utilisateur si l'email n'existe pas déjà
    if not User.objects.filter(email="admin@exemple.com").exists():
        User.objects.create(
            nom="Administrateur Système",
            email="admin@exemple.com",
            password=make_password("admin123"), # Toujours hacher le mot de passe !
            role=role_admin
        )

class Migration(migrations.Migration):

    # dependencies = [
    #     ('ton_app', '0001_initial'), # Doit pointer vers ta migration précédente
    # ]

    dependencies = [
        ('app_contact', '0006_table_role_de_user'),
    ]

    operations = [
        migrations.RunPython(creer_admin_par_defaut),
    ]
    
    
    