# Generated by Django 5.2.8 on 2026-02-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_contact', '0007_administrateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueRetentionSetting',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('retention_years', models.PositiveSmallIntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'historique_retention_setting',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('READ', 'Lecture'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression')], max_length=10)),
                ('app_label', models.CharField(blank=True, default='', max_length=80)),
                ('model_name', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('object_repr', models.CharField(blank=True, default='', max_length=255)),
                ('date_action', models.DateField(auto_now_add=True)),
                ('heure_action', models.TimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('ip', models.CharField(blank=True, default='', max_length=64)),
                ('details', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques_actions', to='app_contact.user')),
            ],
            options={
                'db_table': 'historique_user',
                'ordering': ['-date_action', '-heure_action'],
                'indexes': [models.Index(fields=['date_action'], name='historique__date_ac_2a64cb_idx'), models.Index(fields=['action'], name='historique__action_2345ec_idx'), models.Index(fields=['app_label', 'model_name'], name='historique__app_lab_d41ca8_idx')],
            },
        ),
    ]
