# Generated by Django 5.2.8 on 2026-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_historique', '0002_alter_historiqueuser_user_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueuser',
            name='action',
            field=models.CharField(choices=[('CREATE', 'CREATE'), ('READ', 'READ'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='historiqueuser',
            name='app_label',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='historiqueuser',
            name='date_action',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historiqueuser',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historiqueuser',
            name='model_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
