# Generated by Django 5.2.8 on 2025-12-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0005_projetsfirstspeciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projetmesrealisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='static/images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
