# Generated by Django 5.2.8 on 2025-12-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0007_projetphotodeprofil'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetAproposDeMoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
