# Generated by Django 5.2.8 on 2025-12-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0008_projetaproposdemoi'),
    ]

    operations = [
        migrations.CreateModel(
            name='MesCompetencesCles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, help_text='Le nom de la compétence (ex: Python, Gestion de projet)', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Compétence clé',
                'verbose_name_plural': 'Mes compétences clés',
                'ordering': ['-created_at'],
            },
        ),
    ]
