# Generated by Django 5.2.8 on 2025-12-26 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0009_mescompetencescles'),
    ]

    operations = [
        migrations.AddField(
            model_name='mescompetencescles',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AddField(
            model_name='projetaproposdemoi',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher la section'),
        ),
        migrations.AddField(
            model_name='projetmesrealisations',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AddField(
            model_name='projetphotodeprofil',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher cette photo'),
        ),
        migrations.AddField(
            model_name='projetscards',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AddField(
            model_name='projetsfirstspeciality',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AlterField(
            model_name='mescompetencescles',
            name='nom',
            field=models.CharField(blank=True, help_text='Le nom de la compétence (ex: Python)', max_length=100, null=True, unique=True),
        ),
    ]
