# Generated by Django 5.2.8 on 2025-12-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0010_mescompetencescles_est_visible_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetaproposdemoi',
            options={'ordering': ['-created_at'], 'verbose_name': 'A propos de Moi', 'verbose_name_plural': 'A propos de Moi'},
        ),
    ]
