# Generated by Django 5.2.8 on 2025-12-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0011_alter_projetaproposdemoi_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projetmesrealisations',
            options={'ordering': ['-created_at'], 'verbose_name': 'Réalisation', 'verbose_name_plural': 'Mes Réalisations'},
        ),
        migrations.AlterModelOptions(
            name='projetphotodeprofil',
            options={'ordering': ['-created_at'], 'verbose_name': 'Photo de profil', 'verbose_name_plural': 'Ma Photo de profil'},
        ),
        migrations.AlterModelOptions(
            name='projetscards',
            options={'ordering': ['-created_at'], 'verbose_name': 'Témoignage', 'verbose_name_plural': 'Témoignages Clients'},
        ),
        migrations.AlterModelOptions(
            name='projetsfirstspeciality',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ma Photo de Spécialisation', 'verbose_name_plural': 'Mes Photos de Spécialisation'},
        ),
    ]
