# Generated by Django 5.2.8 on 2025-12-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0012_alter_projetmesrealisations_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReseauSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=20, unique=True)),
                ('url', models.URLField()),
                ('est_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Réseau Social',
                'verbose_name_plural': 'Réseaux Sociaux',
            },
        ),
    ]
