# Generated by Django 5.2.8 on 2026-01-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0013_reseausocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mescompetencescles',
            name='nom',
            field=models.CharField(help_text='Le nom de la compétence (ex: Python)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='projetaproposdemoi',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetmesrealisations',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetmesrealisations',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetmesrealisations',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projetphotodeprofil',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projetsfirstspeciality',
            name='description_speciality',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='projetsfirstspeciality',
            name='images',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
