# Generated by Django 5.2.8 on 2026-01-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0014_alter_mescompetencescles_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseausocial',
            name='nom',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram')], max_length=20, unique=True),
        ),
    ]
