# Generated by Django 5.2.8 on 2026-01-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0015_alter_reseausocial_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetmesrealisations',
            name='compteur_demo_live',
            field=models.PositiveIntegerField(default=0, verbose_name='Clics Démo Live'),
        ),
    ]
