# Generated by Django 5.2.8 on 2026-02-02 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0016_projetmesrealisations_compteur_demo_live'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseausocial',
            name='nom',
            field=models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('twitter', 'X (Twitter)'), ('instagram', 'Instagram')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='url',
            field=models.CharField(help_text='Email (si nom=email) ou URL (pour les autres).', max_length=200),
        ),
    ]
