# Generated by Django 5.2.8 on 2026-02-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0017_alter_reseausocial_nom_alter_reseausocial_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetscards',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
        ),
    ]
