# Generated by Django 5.2.8 on 2026-02-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0018_projetscards_fingerprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mescompetencescles',
            options={'ordering': ['nom'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AlterModelOptions(
            name='projetaproposdemoi',
            options={'verbose_name': 'À propos de moi', 'verbose_name_plural': 'À propos de moi'},
        ),
        migrations.AlterModelOptions(
            name='projetmesrealisations',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Mes Projets'},
        ),
        migrations.AlterModelOptions(
            name='projetphotodeprofil',
            options={'verbose_name': 'Photo de profil', 'verbose_name_plural': 'Photo de profil'},
        ),
        migrations.AlterModelOptions(
            name='reseausocial',
            options={'ordering': ['nom'], 'verbose_name': 'Réseau social', 'verbose_name_plural': 'Réseaux sociaux'},
        ),
        migrations.RemoveField(
            model_name='projetaproposdemoi',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projetphotodeprofil',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='mescompetencescles',
            name='nom',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projetaproposdemoi',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AlterField(
            model_name='projetmesrealisations',
            name='compteur_demo_live',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projetphotodeprofil',
            name='est_visible',
            field=models.BooleanField(default=True, verbose_name='Afficher sur le site'),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='reseausocial',
            name='url',
            field=models.CharField(max_length=255),
        ),
    ]
