# Generated by Django 5.2.8 on 2026-02-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0019_alter_mescompetencescles_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetmesrealisations',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetphotodeprofil',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='projetscards',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='projetsfirstspeciality',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
