# Generated by Django 5.2.8 on 2026-02-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0020_alter_projetmesrealisations_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reseausocial',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
