# Generated by ChatGPT on 2026-02-13
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_acceuil", "0021_alter_reseausocial_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoLiveClickEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("clicked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=255)),
                ("session_key", models.CharField(blank=True, default="", max_length=64)),
                (
                    "realisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_live_clicks",
                        to="app_acceuil.projetmesrealisations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Clic Démo Live",
                "verbose_name_plural": "Clics Démo Live",
            },
        ),
        migrations.AddIndex(
            model_name="demoliveclickevent",
            index=models.Index(fields=["realisation", "clicked_at"], name="app_acceui_realisat_4e2a50_idx"),
        ),
        migrations.AddIndex(
            model_name="demoliveclickevent",
            index=models.Index(fields=["clicked_at"], name="app_acceui_clicked__0f2e0b_idx"),
        ),
    ]
