# Generated by Django 5.2.8 on 2026-02-13 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_acceuil', '0022_demoliveclickevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='demoliveclickevent',
            new_name='app_acceuil_realisa_8b0be6_idx',
            old_name='app_acceui_realisat_4e2a50_idx',
        ),
        migrations.RenameIndex(
            model_name='demoliveclickevent',
            new_name='app_acceuil_clicked_ef41a0_idx',
            old_name='app_acceui_clicked__0f2e0b_idx',
        ),
    ]
