# # # Generated by Django 5.2.8 on 2026-01-13 06:05



from django.db import migrations

def create_default_menus(apps, schema_editor):
    Menu = apps.get_model('app_user', 'Menu')

    data = [
        ('Gestion des Utilisateurs', 'menu_ventes'),
        ('Gestion d\'Affichage du Site', 'menu_stocks'),
        ('Factures', 'menu_factures'),
        ('Rapports', 'menu_rapports'),
    ]    
    for nom, code in data:
        Menu.objects.get_or_create(code_menu=code, defaults={'nom': nom})

class Migration(migrations.Migration):
    dependencies = [('app_user', '0001_initial')]
    operations = [migrations.RunPython(create_default_menus)]
    
    
    
    