# Generated by Django 5.2.8 on 2026-01-18 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0003_alter_user_email'),
        ('app_user', '0002_setup_menus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuacces',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contact.user'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
