# Generated by Django 5.2.8 on 2026-02-01 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contact', '0007_administrateur_role'),
        ('app_user', '0003_alter_menuacces_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='code_menu',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='RoleMenuAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_visible', models.BooleanField(default=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.menu')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contact.role')),
            ],
            options={
                'unique_together': {('role', 'menu')},
            },
        ),
        migrations.DeleteModel(
            name='MenuAcces',
        ),
    ]
